name: mindmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  go_router: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
